import torch, torch.nn.functional as fu
import pandas as pd
import seaborn as sns

long_and_rare_sentences = [
    "Beneath the chiaroscuro of twilight, the mariner contemplated the phosphorescent tide, whose argent flickers seemed to murmure forgotten epics across the indifferent shoreline.",
    "The antiquarian's laconic remark concealed a baroque intellect, for he delighted in obscure manuscripts, labyrinthine annotations, and the sepulchral hush of dust-laden archives.",
    "At dawn, the botanic conservatory exuded a mellifluous fragrance, where heliotropic blossoms quivered beside opalescent glass panes and vitrified dew.",
    "Her peregrine thoughts wandered through a chiaroscurist cityscape, where gilded spires, oblique alleyways, and rain-slick cobblestones formed an almost oneiric geometry.",
    "The orator's rhetoric, though ostensibly perspicuous, was laced with abstruse allusions, making the audience alternately rapturous, bewildered, and faintly disquieted.",
    "An austere monastery perched upon the escarpment, its bell tower resonant with a sonorous cadence that seemed to sanctify the surrounding austerity.",
    "He sifted through the palimpsest of his family's lore, uncovering a motley succession of prodigals, matriarchs, and impecunious dreamers.",
    "The librarian navigated the stacks with assiduous care, retrieving an erudite treatise on etymology and a rare folio bound in cracked vellum.",
    "A languid breeze traversed the veranda, carrying the ephemeral scent of magnolia, rain-soaked cedar, and something ineffably nostalgic.",
    "The physician's prognosis was guarded, yet his demeanor remained imperturbable, as though stoicism itself had been meticulously cultivated in his bones.",
    "Under the coruscant marquee lights, the carnival acquired a delirious splendor, where acrobats, illusionists, and itinerant musicians converged in exuberant disarray.",
    "She possessed a mordant wit, one capable of puncturing pomposity with surgical precision while never forfeiting elegance or restraint.",
    "The corridor seemed interminable, lined with sepia portraits, arabesque molding, and a sequence of doors that invited both curiosity and trepidation.",
    "His narrative unfolded with exacting symmetry, yet beneath its polished surface lurked a brooding cadence of regret and unresolved yearning.",
    "A contingent of ornithologists observed the avian migration with meticulous zeal, noting barometric shifts, thermals, and the birds' uncanny navigational verve.",
    "The diplomat's rejoinder was measured and oblique, balancing tactful diplomacy with a subtle undercurrent of admonition that no one present could ignore.",
    "In the ossified village square, time appeared to congeal, while the clocktower cast a stern shadow over the amber façades.",
    "Her atelier was a sanctum of pigment, charcoal, and unfinished canvases, each surface bearing the restless signature of creative ferment.",
    "The tempest arrived with truculent force, battering shutters, bending branches, and transforming the placid avenue into a torrent of glimmering chaos.",
    "He admired the numinous quiet of the chapel, where stained glass fractured sunlight into prismatic shards of reverence and repose.",
    "The edifice, though weathered, retained an imperious grandeur, its buttresses and cornices testifying to an age of prodigious craftsmanship.",
    "A sybaritic feast awaited the guests, replete with saffron rice, lacquered fruits, and pastries so delicate they seemed nearly intangible.",
    "Her diction was recherché, yet never contrived; every syllable arrived with the assurance of a connoisseur selecting rare gems.",
    "The expedition pressed onward through the umbrageous forest, where lianas tangled overhead and the air felt thick with primordial expectancy.",
    "A tenebrous cloud bank gathered beyond the horizon, its insinuating mass promising either rain, revelation, or ruin.",
    "The professor's discourse traversed philology, metaphysics, and historiography, weaving them together with a dexterity that left even seasoned scholars astonished.",
    "He maintained an ascetic routine, subsisting on frugal meals, rigorous exercise, and the disciplined silence of predawn contemplation.",
    "The concert hall resonated with sonorous brass and glistening strings, producing a cathartic swell that seemed to dissolve the listeners' fatigue.",
    "Her expression remained inscrutable, a mask of placid composure that obscured the maelstrom of calculations behind her eyes.",
    "The alchemist's laboratory contained alembics, retorts, and jars of iridescent powders, all arranged with ritualistic exactitude.",
    "A voluptuary of language, he savored obsolete words, rare idioms, and the velvety cadence of impeccably turned phrases.",
    "The symposium concluded with convivial applause, though several participants carried home a lingering sense of conceptual vertigo.",
    "Within the cloistered courtyard, ivy climbed the walls with insistent vitality, softening the severe geometry of the stone arches.",
    "The emissary's arrival was punctilious, marked by immaculate attire, deferential gestures, and a portfolio of carefully calibrated assurances.",
    "She read the epistle slowly, savoring its elegiac tone and the delicate melancholy embedded in each restrained sentence.",
    "The glacier advanced with glacial deliberation, a colossal testament to patience, pressure, and the inexorable arithmetic of time.",
    "His satire was incisive yet urbane, exposing civic absurdities while preserving enough levity to avoid outright cynicism.",
    "The bazaar overflowed with opulent textiles, brass lamps, and spice pyramids that shimmered like miniature dunes under the sun.",
    "A phantasmagoric dream had left him unsettled, crowded with mirrored corridors, mute strangers, and doors that opened onto impossible skies.",
    "The archivist handled the brittle letters with near-reverential delicacy, as though each page contained a fragile ember of lived history.",
    "Her laughter was contagiously pellucid, cutting through the room like a clear bell struck in a quiet cathedral.",
    "The engineer devised a judicious solution, elegant in its simplicity and robust enough to withstand the most capricious conditions.",
    "Amid the sultry evening, fireflies traced fugitive sigils through the garden, lending the hedges an almost thaumaturgic glow.",
    "The judge delivered his verdict in a grave, unornamented cadence that conveyed authority without theatricality.",
    "He found solace in the recondite volumes of natural philosophy, where obscure diagrams and antiquated arguments still possessed latent charm.",
    "The waterfront district shimmered after rain, each puddle reflecting neon filaments and the restless choreography of passing traffic.",
    "Her remarks were terse but incisive, each one landing with the precision of a well-honed chisel against brittle stone.",
    "The belligerent wind worried the eaves, whistling through the rafters with a keening, almost mournful persistence.",
    "The orchestra's finale was incandescent, a dazzling concatenation of motifs that surged, dissolved, and returned in triumphant recurrence.",
    "He cultivated a fastidious aesthetic, preferring unadorned surfaces, restrained palettes, and objects whose provenance was impeccable.",
    "The narrator's tone was ruminative, moving gracefully between irony, tenderness, and a quietly devastating sense of loss.",
    "A peregrination through the old quarter revealed arcades, reliquaries, and weathered shopfronts redolent of forgotten commerce.",
    "The apothecary's shelves were crowded with tinctures, powders, and aromatic resins, each labeled in a hand both elegant and archaic.",
    "She approached the podium with unassuming poise, then delivered a lucid, penetrating address that altered the tenor of the room.",
    "The moon hung above the estuary like a polished coin, rendering the water strangely sepulchral and serene.",
    "His scholarship was meticulous, but it also possessed a rare lyricism, as if analysis and wonder had agreed to coexist.",
    "The palace corridors were adorned with filigreed lamps, mirrored alcoves, and tapestries whose colors had mellowed into sumptuous obscurity.",
    "A murmuration of starlings wheeled overhead, their collective motion resembling a living manuscript written in dark ink.",
    "The coterie gathered beneath the pergola, exchanging epigrams, gossip, and impeccably timed insinuations with cultivated ease.",
    "Her patience was prodigious, a virtue that enabled her to endure bureaucratic delays without visible rancor.",
    "The cavern breathed cold air and mineral dampness, while its walls glimmered with a faint, chthonic lustre.",
    "He composed the letter with deliberate care, choosing words whose simplicity concealed a profound and inexpressible affection.",
    "The festival had an exuberant, almost bacchanalian energy, though beneath the revelry lay a subtle sense of communal memory.",
    "She possessed a keen aptitude for discernment, separating the essential from the ornamental with enviable swiftness.",
    "The archivists discovered a cryptic ledger, its entries compressed into a kind of mnemonic shorthand intelligible only to the initiated.",
    "At the summit, the air grew rarefied, and the panorama unfolded with alpine majesty across innumerable ridgelines.",
    "The apse glowed with filtered light, giving the sanctuary an aura of devotional stillness and suspended time.",
    "His repartee was elegant but merciless, arriving with such grace that even its sharpest barbs seemed almost courteous.",
    "The confectioner's display was a riot of candied violets, pralines, and marzipan ornaments arranged with aesthetic exuberance.",
    "A rustling in the hedgerow suggested some furtive creature, though the darkness rendered all certainty delightfully elusive.",
    "The lecturer's examples were vivid and apposite, though she occasionally lapsed into a delectably pedantic digression.",
    "Her composure during the crisis was exemplary, as though panic had simply overlooked her altogether.",
    "The old ferry chugged across the river, leaving behind a wake that gleamed like torn silver in the dusk.",
    "He read the travelogue with vicarious hunger, imagining deserts, citadels, and markets saturated with unfamiliar fragrances.",
    "The gallery's silence felt ceremonial, broken only by the almost imperceptible shuffle of contemplative visitors.",
    "A keen-eyed apprentice sorted the gemstones, distinguishing topaz from citrine by subtle chromatic variances.",
    "The storm abated, leaving behind a hushed, saturated landscape that seemed newly minted by the rain.",
    "Her prose possessed an ineffable shimmer, balancing austerity and ornament with consummate control.",
    "The shepherd's whistle echoed across the moor, sparse yet unmistakable, like a thread drawn through open air.",
    "He favored a circumspect approach, advancing cautiously through negotiations until every hidden contingency had been addressed.",
    "The ancient well, encircled by moss and lichen, exuded a quiet, almost ritualistic gravity.",
    "She admired the manuscript's marginalia, where successive readers had inscribed their doubts, corrections, and moments of astonishment.",
    "The observatory dome rotated with mechanical grace, revealing a firmament crowded with remote and glittering intimations.",
    "His arrival was unheralded, yet somehow the room seemed to reorganize itself around his unspoken authority.",
    "The carpenter chose each plank with scrupulous attention, seeking grain, strength, and a color that would mellow beautifully.",
    "In the pale predawn, the village was so still it felt suspended between memory and awakening.",
    "The skeptic offered a sardonic smile, but his gaze betrayed a flicker of genuine curiosity.",
    "She arranged the porcelains with painstaking symmetry, creating a tableau of fragile brilliance and exacting restraint.",
    "The river delta, fecund and unruly, spread into innumerable channels that glinted beneath the humid sun.",
    "His explanation was coherent yet labyrinthine, requiring patience, annotation, and a willingness to revisit every premise.",
    "The choir's harmonies rose with almost liturgical solemnity, filling the nave with a velvety, transfiguring resonance.",
    "A solitary heron stood motionless in the shallows, an ascetic silhouette against the rippled opalescence of morning water.",
    "The merchant spoke in a congenial murmur, though his eyes retained the shrewd vigilance of someone counting outcomes.",
    "Her imagination was inexhaustible, generating improbable landscapes, unlikely characters, and entire civilizations within a single glance.",
    "The antiquated clock mechanism ticked with stubborn regularity, defying the entropy that had claimed everything around it.",
    "He relished the sesquipedalian flourish of the lecture, especially when it illuminated a surprisingly simple truth.",
    "The hillside chapel, isolated and wind-burnished, seemed less built than coaxed into being by devotion itself.",
    "Their alliance was pragmatic rather than affectionate, assembled through necessity and maintained by mutual advantage.",
    "The moonlit avenue shimmered with a taciturn beauty, every tree casting a long, mournful corolla of shadow.",
    "She opened the casket and found a miniature reliquary, its contents wrapped in faded silk and silence.",
    "The magistrate's office was spare and immaculate, its severity softened only by a single fern on the sill.",
    "A sudden hush enveloped the auditorium, as though collective anticipation had crystallized into palpable form.",
    "He spoke with unembellished sincerity, and the simplicity of it made the room feel unexpectedly luminous.",
    "The wind carried the briny odor of the coast, mixed with kelp, salt, and the metallic tang of spray.",
    "Her gaze lingered on the horizon, where clouds amassed in a brooding procession above the waterline.",
    "The garden gate creaked open to reveal a secluded court of roses, stone benches, and ivy-clad arches."
]

small_sentences = [
    "A bird sings.",
    "The sun rises over the quiet hills.",
    "She read a book by the window.",
    "Rain fell softly throughout the afternoon.",
    "The cat slept on the warm blanket.",
    "He walked home after a long day.",
    "A river flows beneath the wooden bridge.",
    "They laughed until their eyes filled with tears.",
    "The market opened early with bright, noisy crowds.",
    "A child carefully stacked colorful blocks on the floor.",
    "The old house stood alone beside the dusty road.",
    "We watched the stars appear one by one.",
    "The painter mixed blue and gold on his palette.",
    "Her voice sounded calm and strangely distant.",
    "The train arrived exactly at midnight.",
    "A small lantern lit the narrow hallway.",
    "The flowers leaned toward the morning light.",
    "He answered the question without hesitation.",
    "The forest path disappeared into thick mist.",
    "Their conversation lasted far longer than expected.",
    "A notebook lay open beside the computer.",
    "The dog chased a leaf across the yard.",
    "She wore a bright scarf on the coldest morning.",
    "The ocean looked silver under the moon.",
    "A message waited unread in the inbox.",
    "They prepared dinner while music played softly.",
    "The window rattled during the stormy night.",
    "He placed the key carefully on the table.",
    "The classroom became silent after the announcement.",
    "A little girl fed crumbs to the sparrows.",
    "The garden smelled like wet earth and jasmine.",
    "She crossed the street before the light changed.",
    "A sudden breeze moved the curtains gently.",
    "The mountain peaks glowed at sunrise.",
    "He forgot his umbrella and got drenched.",
    "The clock on the wall stopped working.",
    "They found a hidden path behind the temple.",
    "A line of ants carried sugar across the floor.",
    "The artist sketched faces in a crowded café.",
    "We listened to the thunder from inside.",
    "The suitcase was heavier than it looked.",
    "Her notebook contained a thousand tiny ideas.",
    "The baker pulled fresh bread from the oven.",
    "He smiled when the letter finally arrived.",
    "A fox darted through the tall grass.",
    "The library smelled of paper and dust.",
    "They shared stories beside the fire.",
    "The bridge shook slightly as trucks passed.",
    "She planted marigolds near the front gate.",
    "A map was pinned above the desk.",
    "The puppy barked at its own reflection.",
    "He practiced the speech until dawn.",
    "The hallway echoed with hurried footsteps.",
    "A bright kite climbed high into the sky.",
    "They packed supplies for the long journey.",
    "The window offered a view of rain-washed streets.",
    "She placed fresh flowers in a glass vase.",
    "The room filled with laughter and warm light.",
    "A train whistle faded into the distance.",
    "He wrote a poem on a scrap of paper.",
    "The children built a fort out of blankets.",
    "The hillside was dotted with wild yellow blooms.",
    "She found an old photograph in the drawer.",
    "A candle burned steadily beside the mirror.",
    "The riverbank glistened after the heavy rain.",
    "He listened carefully to every word.",
    "The shopkeeper arranged fruit in neat rows.",
    "They rested under a tree at noon.",
    "A pale moon hung above the village.",
    "The mail carrier left a package at dawn.",
    "She answered with a quiet nod.",
    "The road curved sharply around the cliff.",
    "A violin played somewhere beyond the wall.",
    "He carried the basket with both hands.",
    "The room smelled faintly of coffee and cinnamon.",
    "They watched the fireworks bloom overhead.",
    "A notebook page fluttered in the breeze.",
    "The taxi waited outside in the rain.",
    "She tied her shoelaces and ran.",
    "The orchard was alive with buzzing bees.",
    "He paused at the gate before entering.",
    "A blue jacket hung on the chair.",
    "The candles melted slowly through the night.",
    "They heard footsteps approaching the porch.",
    "She folded the map into a square.",
    "The children splashed through shallow puddles.",
    "A soft song drifted from the kitchen.",
    "He kept the promise he had made.",
    "The clouds broke apart after sunset.",
    "She carried a basket full of apples.",
    "A whisper moved through the crowded hall.",
    "The hillside path twisted between the trees.",
    "He opened the door and stepped inside.",
    "The rain stopped, leaving everything washed clean.",
    "A tiny boat rocked on the lake.",
    "They lit the lanterns before dinner.",
    "She looked up and saw the comet.",
    "The morning felt cool and unusually still.",
    "He turned the page and kept reading.",
    "A long shadow crossed the empty field.",
    "The final bell rang, ending the day.",
    "She smiled, and the whole room changed."
]

def get_program_texts():
    return ['program', 'programmer', 'programming', 'programmed', 'programs']

def rare_words():
    return ["electroencephalography", "antidisestablishmentarianism", "electromagnetohydrodynamics"]

def sentence_matrix(sentences, tokenizer, model):
    store_embeddings = {}
    for sentence in sentences:
        text = sentence
        
        tokens = tokenizer.tokenize(sentence)
        token_id = tokenizer.convert_tokens_to_ids(tokens)
        input_id_ = torch.tensor(token_id)
        embeddings = model.get_input_embeddings()(input_id_)
        store_embeddings[sentence] = embeddings.mean(dim=0)

    sim_scores = {}
    for x in sentences:
        sim_scores[x]=[]
        for y in sentences:
            s1 = store_embeddings[x]
            s2 = store_embeddings[y]
            sim_scores[x].append(fu.cosine_similarity(s1, s2, dim=0).item())

    similarity_df = pd.DataFrame(sim_scores, index=["s1", "s2", "s3", "s4", "s5"])
    similarity_df.columns = ["s1", "s2", "s3", "s4", "s5"]

    print(similarity_df)
    sns.heatmap(pd.DataFrame(sim_scores, index=sentences), cmap='Greys')